/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as sidebarLayoutRouteImport } from './routes/(sidebar)/layout'
import { Route as sidebarPageRouteImport } from './routes/(sidebar)/page'
import { Route as sidebarAgentsPageRouteImport } from './routes/(sidebar)/agents/page'
import { Route as sidebarAgentsAgentIdPageRouteImport } from './routes/(sidebar)/agents/$agentId/page'

const sidebarLayoutRoute = sidebarLayoutRouteImport.update({
  id: '/(sidebar)',
  getParentRoute: () => rootRouteImport,
} as any)
const sidebarPageRoute = sidebarPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => sidebarLayoutRoute,
} as any)
const sidebarAgentsPageRoute = sidebarAgentsPageRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => sidebarLayoutRoute,
} as any)
const sidebarAgentsAgentIdPageRoute =
  sidebarAgentsAgentIdPageRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => sidebarLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof sidebarPageRoute
  '/agents/': typeof sidebarAgentsPageRoute
  '/agents/$agentId/': typeof sidebarAgentsAgentIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof sidebarPageRoute
  '/agents': typeof sidebarAgentsPageRoute
  '/agents/$agentId': typeof sidebarAgentsAgentIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(sidebar)': typeof sidebarLayoutRouteWithChildren
  '/(sidebar)/': typeof sidebarPageRoute
  '/(sidebar)/agents/': typeof sidebarAgentsPageRoute
  '/(sidebar)/agents/$agentId/': typeof sidebarAgentsAgentIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents/' | '/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/agents/$agentId'
  id:
    | '__root__'
    | '/(sidebar)'
    | '/(sidebar)/'
    | '/(sidebar)/agents/'
    | '/(sidebar)/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  sidebarLayoutRoute: typeof sidebarLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(sidebar)': {
      id: '/(sidebar)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof sidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sidebar)/': {
      id: '/(sidebar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof sidebarPageRouteImport
      parentRoute: typeof sidebarLayoutRoute
    }
    '/(sidebar)/agents/': {
      id: '/(sidebar)/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof sidebarAgentsPageRouteImport
      parentRoute: typeof sidebarLayoutRoute
    }
    '/(sidebar)/agents/$agentId/': {
      id: '/(sidebar)/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof sidebarAgentsAgentIdPageRouteImport
      parentRoute: typeof sidebarLayoutRoute
    }
  }
}

interface sidebarLayoutRouteChildren {
  sidebarPageRoute: typeof sidebarPageRoute
  sidebarAgentsPageRoute: typeof sidebarAgentsPageRoute
  sidebarAgentsAgentIdPageRoute: typeof sidebarAgentsAgentIdPageRoute
}

const sidebarLayoutRouteChildren: sidebarLayoutRouteChildren = {
  sidebarPageRoute: sidebarPageRoute,
  sidebarAgentsPageRoute: sidebarAgentsPageRoute,
  sidebarAgentsAgentIdPageRoute: sidebarAgentsAgentIdPageRoute,
}

const sidebarLayoutRouteWithChildren = sidebarLayoutRoute._addFileChildren(
  sidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  sidebarLayoutRoute: sidebarLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
